apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-managed-stack
  annotations:
    kargo.akuity.io/color: indigo
spec:
  # Subscribe directly to the Warehouse for automatic deployments
  requestedFreight:
    - origin:
        kind: Warehouse
        name: security-scan-repo
      sources:
        direct: true

  # Update stacks/dev.yaml with the latest commit from freight
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/lichtie/kargo-manifests
            checkout:
              - branch: main
                path: ./manifests
        - uses: yaml-update
          config:
            path: ./manifests/stacks/dev.yaml
            updates:
              - key: spec.commit
                value: ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}
        - uses: git-commit
          as: commit
          config:
            path: ./manifests
            message: 'Update dev to ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}'
        - uses: git-push
          config:
            path: ./manifests
            targetBranch: main
        - uses: argocd-update
          config:
            apps:
              - name: security-scanner
                sources:
                  - repoURL: https://github.com/lichtie/kargo-manifests
                    desiredRevision: ${{ outputs.commit.commit }}

  verification:
    analysisTemplates:
      - name: pulumi-stack-success
        args:
          - name: commit-id
            value: ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}
