apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: kargo-managed-stack
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/lichtie/kargo-manifests
  username: lichtie
  password: GITHUB_TOKEN
