apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: approvalgatedev
  namespace: kargo-managed-stack
  annotations:
    kargo.akuity.io/color: red
spec:
  # Subscribe directly to the Warehouse for automatic deployments
  requestedFreight:
    - origin:
        kind: Warehouse
        name: security-scan-repo
      sources:
        direct: true

  # Update stacks/devpreview.yaml with the latest commit from freight
  promotionTemplate:
    spec:
      steps:
