apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: approvalgateqa
  namespace: kargo-managed-stack
  annotations:
    kargo.akuity.io/color: red
spec:
  # This is an approval gate - freight that has completed dev stage waits here
  # for manual approval before being promoted to downstream stages (qapreview → qa)
  requestedFreight:
    - origin:
        kind: Warehouse
        name: security-scan-repo
      sources:
        direct: false
        stages:
          - dev
          - dev2

  # Minimal promotion template to enable manual approval requirement
  # Without autoPromotionEnabled, promotions must be manually triggered
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/lichtie/kargo-manifests
            checkout:
              - branch: main
                path: ./approval-check
