apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: approvalgatedev
  namespace: kargo-managed-stack
  annotations:
    kargo.akuity.io/color: red
spec:
  # This is an approval gate - freight from the warehouse waits here for manual approval
  # before being promoted to downstream stages (devpreview → dev)
  requestedFreight:
    - origin:
        kind: Warehouse
        name: security-scan-repo
      sources:
        direct: true

  # Minimal promotion template to enable manual approval requirement
  # Without autoPromotionEnabled, promotions must be manually triggered
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/lichtie/kargo-manifests
            checkout:
              - branch: main
                path: ./approval-check
