apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: kargo-managed-stack
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: security-scan-repo
      sources:
        direct: false
        stages:
          - qapreview

  # Update stacks/qa.yaml with the latest commit from freight
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/lichtie/kargo-manifests
            checkout:
              - branch: main
                path: ./manifests
        - uses: yaml-update
          config:
            path: ./manifests/stacks/qa.yaml
            updates:
              - key: spec.commit
                value: ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}
        - uses: git-commit
          as: commit
          config:
            path: ./manifests
            message: 'Update qa to ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}'
        - uses: git-push
          config:
            path: ./manifests
            targetBranch: main

  verification:
    analysisTemplates:
      - name: pulumi-stack-update-success
    args:
      - name: commit-id
        value: ${{ commitFrom("https://github.com/lichtie/security-scanner").ID }}
      - name: stackName
        value: qa
