apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pulumi-stack-update-success
  namespace: kargo-managed-stack
spec:
  args:
    - name: commit-id
    - name: stackName
    - name: pulumi-token
      valueFrom:
        secretKeyRef:
          name: pulumisecret
          key: PULUMI_ACCESS_TOKEN
  metrics:
    - name: check-pulumi-update
      initialDelay: 5m
      successCondition: result.updates[0].result == "succeeded" && result.updates[0].environment["git.head"] == "{{args.commit-id}}" && result.updates[0].kind == "update"
      provider:
        web:
          url: https://api.pulumi.com/api/stacks/elisabeth-demo/security-scanner/{{args.stackName}}/updates?pageSize=1&page=1
          headers:
            - key: Authorization
              value: "token {{args.pulumi-token}}"
            - key: Accept
              value: application/json
          jsonPath: "{$}"
